View 구조 수정 및 파일 폴더링
M1zz/BamiLog pull request #1
Opened 2023-01-13 22:55 UTC by steady-on

## 개요
- 파일 내부의 구조 분리 및 Foldering
- UX를 고려한 View의 UI 및 디자인 수정
- Button 동작 로직 수정

## 작업사항
### 파일 내부의 구조 분리 및 Foldering
- View와 Model을 각각 파일로 분리
- 분리한 파일을 Foldering

### UX를 고려한 View의 UI 및 디자인 수정

#### ContentView
- ContentView의 Header 수정
- Scroll로 인해 Header가 가려지지 않도록 구조개선
- Grid를 사용하여 Button 배열의 구조 변경
- 무분별하게 달려있던 .sheet 메서드를 ScrollView에 정리
- wheel style의 Picker가 많은 하위뷰의 특성상 조작 중에 뷰가 닫힐 가능성이 높으므로 모달뷰를 fullScreenCover로 변경

#### Button
- Button의 위치와 순서를 각 용도와 의미하는 바에 맞게 변경
- 강렬한 버튼 색상으로 인해 눈의 피로도가 올라가는 것을 방지하기 위해 테두리를 삭제
- Button의 용도와 목적에 따라 바탕색 통일

#### RecordView
- 하나의 View에서 Switch로 분기되던 코드를 각각의 View 파일로 분리하여 코드 가독성 향상
- View에서 분기되지 않고, 조건에 따라 불러오는 View가 달라지도록 로직 수정
- NavigationTitle을 사용하여 각 뷰마다 제목이 보이도록 수정
- 왼쪽 위는 닫기 혹은 이전 버튼, 오른쪽 위는 저장버튼을 넣어 아이폰 사용자가 익숙한 UI로 구조 변경
- 각 입력 받는 양식을 Form 컴포넌트를 사용하여 UI 개선

## 변경로직
### ContentView
- 각 버튼을 탭하면 isShow 프로퍼티가 toggle되고 buttonStyle에 값이 전달되는 것은 동일
- fullScreenCover에서 buttonStyle의 값에 따라 호출하는 View가 달라지도록 로직 수정
- isShow 프로퍼티를 Binding값으로 하위에 전달하지 않고 환경변수를 사용하여 닫히도록 수정

2023-01-13 22:56 UTC, steady-on commented
너무 졸려서 다른 뷰 수정은 다음기회에 하도록 하겠습니다!

2023-01-14 07:21 UTC, M1zz requested changes
으아아 기여 너무나 감사합니다 :)

혹시 수정요청도 받아주시나요? ㅎ ㅎ

2023-01-14 07:21 UTC, M1zz commented on BamiLog/Extension/View+.swift
> +    func hAlign(_ alignment: Alignment) -> some View {
hAlign 이라는 이름을 보고 어떤 기능을 하는지 잘 모르겠습니다 동사로 시작하는 함수 명으로 만들어진게 저는 명확하게 느껴지는데 어떠신가요?

2023-01-14 07:21 UTC, M1zz commented on BamiLog/RecordView.swift
> +        RecordView(buttonType: .constant(.feeding), isShow: .constant(true))
프리뷰를 고친 이유가 있으신가요?

2023-01-14 07:21 UTC, M1zz commented on BamiLog/RecordView.swift
> +                Text("시간를 선택해주세요") // 오타있어요
오타가 있으면 수정 부탁드립니다 ㅎ ㅎ
오타 찾기가 세상에서 제일 어려워요 ㅠㅠ

2023-01-14 07:39 UTC, steady-on commented on BamiLog/RecordView.swift
> +        RecordView(buttonType: .constant(.feeding), isShow: .constant(true))
아! 이건 매번 시뮬레이터 돌리기가 싫어서 프리뷰 수정해서View 확인하려고 했었던 겁니다.
다시 돌려놓고 Push 한다는걸 깜빡했습니다.

2023-01-14 07:41 UTC, steady-on commented on BamiLog/RecordView.swift
> +                Text("시간를 선택해주세요") // 오타있어요
일단, 오타가 있는 RecordView는 Refactoring 과정에서 호출되지 않는 View입니다!
PR 메세지에 적혀있지만, RecordView 하나에서 switch로 분기되는 부분을 하위 View로 전부 따로 파일분리 했습니다!

2023-01-14 07:55 UTC, steady-on commented on BamiLog/Extension/View+.swift
> +    func hAlign(_ alignment: Alignment) -> some View {
setHorizontalAlign, setVerticalAlign으로 함수명 변경했습니다~!

2023-01-14 09:36 UTC, M1zz commented on BamiLog/RecordView.swift
> +        RecordView(buttonType: .constant(.feeding), isShow: .constant(true))
프리뷰를 적절한 형태로 쓰셨군요 그냥 궁금했었습니다. :)

2023-01-14 09:37 UTC, M1zz commented on BamiLog/RecordView.swift
> +                Text("시간를 선택해주세요") // 오타있어요
감사합니다! 나머지 버려야 할 뷰들은 버려야겠네요

2023-01-14 09:37 UTC, M1zz commented on BamiLog/Extension/View+.swift
> +    func hAlign(_ alignment: Alignment) -> some View {
좋아요!

2023-01-14 09:38 UTC, M1zz approved these changes
승인! 감사합니다 ㅎ ㅎ

2023-01-14 09:38 UTC, merged